Repository goharbor/website, pull requests merged in 2022-04, with the labels that each got.

#324 Update db-auth.md
  docs/administration/configure-authentication/db-auth.md
Labels: target/2.6.0

#325 Update user-permissions-by-role.md
  docs/administration/managing-users/user-permissions-by-role.md
  docs/administration/p2p-preheat/manage-preheat-providers.md
  docs/administration/robot-accounts/_index.md
  docs/working-with-projects/project-configuration/configure-webhooks.md
Labels: target/2.6.0

#328 Cosign blog post and fix in docs #312
  content/blog/cosign-2.5.0.md
  content/blog/img/cosign/cosign-cosign.png
  content/blog/img/cosign/cosign-harbor2-results.png
  content/blog/img/cosign/cosign-harbor2.png
  content/blog/img/cosign/cosign-member.png
  content/blog/img/cosign/cosign-project-prod.png
  content/blog/img/cosign/cosign-project.png
  content/blog/img/cosign/cosign-replicate.png
  content/blog/img/cosign/cosign-replication.png
  content/blog/img/cosign/cosign-robo-secret.png
  content/blog/img/cosign/cosign-robot.png
  content/blog/img/cosign/cosign-user.png
  docs/working-with-projects/working-with-images/sign-images.md
Labels: target/2.5.0

#333 Add video for cosign demo in the blog
  content/blog/cosign-2.5.0.md
Labels: blog
